import {
  buildWorkbookFromMarkdownTables,
  extractMarkdownTables,
} from '../utils/tableExport';
import * as XLSX from 'xlsx';

describe('table export', () => {
  const markdown = [
    '# Power Platform Solution: Sample',
    '',
    '> **Generated by PP-MD** - Power Platform Solution Documentation',
    '> Generated on: 2026-08-03 12:00:00',
    '',
    '## Solution Overview',
    '',
    '- **Display Name:** Sample',
    '- **Version:** 1.0.0',
    '',
    '## Tables & Columns',
    '',
    '### Project (new_project)',
    '',
    '| Property | Value |',
    '|---|---|',
    '| Logical Name | new_project |',
    '',
    '#### Columns',
    '',
    '## Solution Summary',
    '',
    '| Item | Count |',
    '|---|---|',
    '| Tables | 3 |',
    '| Flows | 2 |',
    '',
    '## Security Roles',
    '',
    '| Role | Read | Write |',
    '|---|---|---|',
    '| Admin | Org | Org |',
    '| User | User | None |',
    '',
    '## Solution Dependencies',
    '',
    '| Solution Name | Display Name | Version | Internal |   |',
    '|---|---|---|---|---|',
    '| Contoso Core (2.4.1.0) | Contoso Core |  | ✅ |   |',
    '| Shared Platform (1.9.0) | Shared Platform | 1.9.0 |  |   |',
    '',
  ].join('\n');

  it('extracts markdown tables and associates them to nearest heading', () => {
    const tables = extractMarkdownTables(markdown);

    expect(tables.length).toBe(4);
    expect(tables[0].heading2).toBe('Tables & Columns');
    expect(tables[0].heading3).toBe('Project (new_project)');
    expect(tables[0].headers).toEqual(['Property', 'Value']);
  });

  it('builds workbook with contents first and links to each table tab', () => {
    const workbook = buildWorkbookFromMarkdownTables(markdown);

    expect(workbook).not.toBeNull();
    expect(workbook?.SheetNames[0]).toBe('Contents');
    expect(workbook?.SheetNames.length).toBeGreaterThanOrEqual(3);

    const contents = workbook?.Sheets.Contents;
    expect(contents?.['!ref']).toBeDefined();
    expect(contents?.A1?.v).toContain('Power Platform Solution -');
    expect(contents?.A2?.v).toContain('Generated by PP-MD');
    expect(contents?.A3?.v).toContain('Generated on:');

    expect(String(contents?.A5?.v || '').length).toBeGreaterThan(0);
    expect(String(contents?.A5?.v || '')).not.toBe('Field');
    expect(String(contents?.B5?.v || '').length).toBeGreaterThan(0);

    const linkCells = Object.entries(contents || {})
      .filter(([addr, cell]) => /^B\d+$/.test(addr) && typeof cell === 'object' && cell !== null && 'l' in (cell as object))
      .map(([, cell]) => cell as { v?: string; l?: { Target?: string } });

    expect(linkCells.length).toBeGreaterThan(0);
    expect((linkCells[0].v || '').length).toBeGreaterThan(0);
    expect(linkCells[0].l?.Target || '').toContain("'!A1");

    expect(workbook?.SheetNames.some((name) => /Project/.test(name))).toBe(true);

    const projectSheetName = workbook?.SheetNames.find((name) => /Project/.test(name));
    expect(projectSheetName).toBeDefined();
    if (projectSheetName) {
      expect(workbook?.Sheets[projectSheetName]?.['!ref']).toBeDefined();
    }
  });

  it('extracts dependency version from solution name and removes internal/empty columns', () => {
    const workbook = buildWorkbookFromMarkdownTables(markdown);
    expect(workbook).not.toBeNull();

    const dependencySheetName = workbook?.SheetNames.find((name) => /Solution Dependencies/i.test(name));
    expect(dependencySheetName).toBeDefined();
    if (!dependencySheetName || !workbook) return;

    const ws = workbook.Sheets[dependencySheetName];
    const rows = ws ? XLSX.utils.sheet_to_json(ws, { header: 1, raw: false, defval: '' }) as string[][] : [];

    const headerRowIdx = rows.findIndex((row) => row.includes('Solution Name') && row.includes('Version'));
    expect(headerRowIdx).toBeGreaterThanOrEqual(0);
    if (headerRowIdx < 0) return;

    const headers = rows[headerRowIdx];
    expect(headers).not.toContain('Internal');
    expect(headers.some((header) => String(header).trim().length === 0)).toBe(false);

    const solutionNameIdx = headers.indexOf('Solution Name');
    const versionIdx = headers.indexOf('Version');
    expect(solutionNameIdx).toBeGreaterThanOrEqual(0);
    expect(versionIdx).toBeGreaterThanOrEqual(0);

    const firstDataRow = rows[headerRowIdx + 1];
    expect(firstDataRow[solutionNameIdx]).toBe('Contoso Core');
    expect(firstDataRow[versionIdx]).toBe('2.4.1.0');
  });

  it('returns null workbook when no markdown tables exist', () => {
    const workbook = buildWorkbookFromMarkdownTables('## Heading\n\nNo table here.');
    expect(workbook).toBeNull();
  });

  it('removes columns with visually blank headers', () => {
    const markdownWithBlankHeaders = [
      '# Demo',
      '',
      '## Blank Header Test',
      '',
      '| Property | Value | \u200B | \u00A0 |',
      '|---|---|---|---|',
      '| Name | Contoso | hidden | hidden2 |',
      '',
    ].join('\n');

    const workbook = buildWorkbookFromMarkdownTables(markdownWithBlankHeaders);
    expect(workbook).not.toBeNull();
    if (!workbook) return;

    const targetSheet = workbook.SheetNames.find((name) => /Blank Header Test/i.test(name));
    expect(targetSheet).toBeDefined();
    if (!targetSheet) return;

    const ws = workbook.Sheets[targetSheet];
    const rows = ws ? XLSX.utils.sheet_to_json(ws, { header: 1, raw: false, defval: '' }) as string[][] : [];
    const headerRow = rows.find((row) => row.includes('Property') && row.includes('Value')) || [];

    expect(headerRow).toEqual(['Property', 'Value']);
  });
});
